model:
  base_name: "cardiffnlp/twitter-roberta-base-sentiment-latest" # RINOMINARE base_model
  hub_id: "gm84/sentiment-analysis-deploy" # RINOMINARE hub_model
  threshold_f1: 0.75 

data:
  dataset_name: "mteb/tweet_sentiment_extraction"
  backtest_chunks: 15 # numero finestre temporali (batch) in cui suddividere il train set

monitoring:
  monitoring_dataset_id: "gm84/sentiment-analysis-monitoring"
  
  # Dizionario dei drift: specifichiamo solo i batch in cui alterare i dati
  # Tutti gli altri batch non elencati saranno considerati traffico standard
  drift_schedule:
    5:
      target_class: 2     # 0= negative, 1= neutral, 2 = positive
      imbalance_ratio: 0.90 # Primo calo (moderato)
    11:
      target_class: 2     # 0= negative, 1= neutral, 2 = positive
      imbalance_ratio: 0.96 # Secondo calo (più severo)

  polling:
    interval_seconds: 30 # Intervallo di controllo verso GitHub Actions
    timeout_seconds: 1800  # Timeout massimo (30 minuti)
