model:
  base_name: "cardiffnlp/twitter-roberta-base-sentiment-latest" # RINOMINARE base_model
  hub_id: "gm84/sentiment-analysis-deploy" # RINOMINARE hub_model
  threshold_f1: 0.75 

data:
  dataset_name: "mteb/tweet_sentiment_extraction"
  backtest_chunks: 5 # numero finestre temporali in cui suddividere il train set

monitoring:
  monitoring_dataset_id: "gm84/sentiment-analysis-monitoring"
  imbalance_ratio: 0.9 
  target_class_to_drop: 2 # 0= negative, 1= neutral, 2 = positive
