name: CI Quality Check
on: [push, pull_request, workflow_dispatch]
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: .
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Linting
        run: flake8 .
      - name: Unit Tests
        run: pytest tests/unit/
      - name: Integration Tests
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: pytest tests/integration/
